FROM node:22-alpine

WORKDIR /app

# Instala pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

# Copia manifests
COPY package.json pnpm-lock.yaml ./

# Instala dependências
RUN pnpm install --frozen-lockfile

# Copia código fonte
COPY . .

EXPOSE 3001

CMD ["pnpm", "run", "dev"]
